export const componentCategories = [
	{ value: 'accordion', label: 'Accordion' },
	{ value: 'alert', label: 'Alert' },
	{ value: 'audio', label: 'Audio' },
	{ value: 'avatar', label: 'Avatar' },
	{ value: 'badge', label: 'Badge' },
	{ value: 'badge-group', label: 'Badge Group' },
	{ value: 'button', label: 'Button' },
	{ value: 'calendar', label: 'Calendar' },
	{ value: 'card', label: 'Card' },
	{ value: 'carousel', label: 'Carousel' },
	{ value: 'chart', label: 'Chart' },
	{ value: 'color-picker', label: 'Color Picker' },
	{ value: 'date-picker', label: 'Date Picker' },
	{ value: 'dropdown', label: 'Dropdown' },
	{ value: 'form', label: 'Form' },
	{ value: 'icon', label: 'Icon' },
	{ value: 'image', label: 'Image' },
	{ value: 'input', label: 'Input' },
	{ value: 'list', label: 'List' },
	{ value: 'menu', label: 'Menu' },
	{ value: 'modal', label: 'Modal' },
	{ value: 'notification', label: 'Notification' },
	{ value: 'pagination', label: 'Pagination' },
	{ value: 'popover', label: 'Popover' },
	{ value: 'progress', label: 'Progress' },
	{ value: 'progress-bar', label: 'Progress Bar' },
	{ value: 'slider', label: 'Slider' },
	{ value: 'spinner', label: 'Spinner' },
	{ value: 'table', label: 'Table' },
	{ value: 'text', label: 'Text' },
	{ value: 'time-picker', label: 'Time Picker' },
	{ value: 'tooltip', label: 'Tooltip' },
	{ value: 'video', label: 'Video' },
];
